### ISSUE TITLE
How to control by jsonrpc?

### ISSUE THREAD

**Issue by monchaikwsp** [glorang/plugin.audio.rtlfm#1]
Please suggest me to control, how to evaluate a frequency to play by kodi json rpc.  Thank you in advanced.

**Comment by glorang** [comment]
have a look here : https://github.com/AlbrechtL/rtl_fm_streamer#json-rpc-api

you might be better of with another plugin though, this was really just a test to see if it works. Check the plugins mention in http://openelec.tv/forum/126-3rd-party/75537-fm-radio-receiver-for-kodi-for-the-raspberry-pi-1

**Comment by monchaikwsp** [comment]
Thank you for your kindness.  I already tried to call :-   

http://192.168.1.3:2345/jsonrpc?request={"jsonrpc":"2.0","method":"SetFrequency","params":[106000000]}

The server responsed :- 
{
	"error":	{
		"code":	-32700,
		"message":	"Parse error. Invalid JSON was received by the server."
	}
}

But it only work when running on any PCs like this :- 

http://192.168.1.3:2346/106000000

And I can not call json rpc to select any frequency in a list of your addon (plugin.audio.fmradio).  Do you have any suggestion for me?

**Comment by glorang** [comment]
I don't think you can call the JSON RPC server over HTTP,  here's a telnet example:

    # telnet localhost 2345
    {"method": "SetFrequency", "params": [106000000]}
    {
            "result":       106000000
    }

**Comment by monchaikwsp** [comment]
I used PuTTY to connected to LibreELEC (kodi).  And run telnet followed the above step, a result was displayed same as their.  But nothing happened to LibreELEC.

My intentions is call the JSON RPC over HTTP to listening a radio on LibreELEC.  Is it possible, if I study and modify an addon.py in plugin.audio.fmradio for according to what was intended.  Because I found a list of fm frequency is work whenever I click mouse on any items.

Thank you for your help as well.

**Comment by monchaikwsp** [comment]
Now I do not understand about addon.py in plugin.audio.fmradio.  But I have been to called the JSON RPC over HTTP :- 

http://192.168.1.3:8080/jsonrpc?request={"jsonrpc":"2.0","method":"Addons.ExecuteAddon","id":"1","params":{"wait":false,"addonid":"plugin.audio.fmradio","params":["106000000"]}}

LibreELEC display a list of fm frequency but it does not run any item.  Is it possible, if I call JSON RPC by specify the correctly number of item in a list.

**Comment by monchaikwsp** [comment]
Today, I would like to inform you about according to what was intended.  And I am delighted to offer you for a new source code and appreciate you for kindness.

The new source code, you can called the JSON RPC over HTTP to listen a 106.0 FM radio by :- 

http://192.168.1.3:8080/jsonrpc?request={"jsonrpc":"2.0","method":"Addons.ExecuteAddon","id":"1","params":{"wait":false,"addonid":"plugin.audio.fmradio","params":{"option":"106.0"}}}

**Comment by monchaikwsp** [comment]
# -- Imports ------------------------------------------------
import json,os,sys,urlparse,urllib,urllib2
import xbmc,xbmcplugin,xbmcgui,xbmcaddon

# -- Constants ----------------------------------------------
ADDON_ID = 'plugin.audio.fmradio'

# -- Settings -----------------------------------------------
settings = xbmcaddon.Addon(id=ADDON_ID)

# -- I18n ---------------------------------------------------
language = xbmcaddon.Addon(id=ADDON_ID).getLocalizedString

# -- Functions ----------------------------------------------

# -- Classes ------------------------------------------------
class FMRadio(xbmcaddon.Addon):

	def __init__ (self):
#		xbmcaddon.Addon.__init__(self,id=ADDON_ID)
		self.language	= self.getLocalizedString
		self.addon_id	= self.getAddonInfo('id')
		self.icon	= self.getAddonInfo('icon')
		self.version	= self.getAddonInfo('version')
		self.path	= self.getAddonInfo('path')

	def log(self,message,level=xbmc.LOGDEBUG):
		xbmc.log("[%s-%s]: %s" %(self.addon_id, self.version, message), level=level)

	def notice(self,message):
		self.log(message,xbmc.LOGNOTICE)

	def warning(self,message):
		self.log(message,xbmc.LOGWARNING)

	def error(self,message):
		self.log(message,xbmc.LOGERROR)

	def doOption(self,option):
		if option == "list":
			for freq in range(875,1080):
				self.addStation('{0}'.format(freq*100000),'{0} MHz'.format(float(float(freq)/float(10))))
			xbmcplugin.endOfDirectory(self.addon_handle)
		else:
			freq = float(option)
			self.addStation('{0}'.format(freq*1000000),'FM {0} MHz'.format(freq))
			xbmcplugin.endOfDirectory(self.addon_handle)
			play_item = xbmcgui.ListItem('Radio FM {0} MHz'.format(freq))
			play_item.setInfo('music', {'Title': 'FM {0} MHz'.format(freq), 'Genre': 'Radio'})
			xbmc.Player().play('http://127.0.0.1:2346/{0}/1'.format(freq*1000000), play_item, False)
	
	def addStation(self,freq,title):
		li = xbmcgui.ListItem(title)
		li.setLabel2(freq)
		li.setProperty('IsPlayable', 'true')
		li.setInfo(type = 'Music', infoLabels = {
			"Title": title
		})
		xbmcplugin.addDirectoryItem(
			handle = self.addon_handle,
			url = 'http://127.0.0.1:2346/{0}'.format(freq),
			listitem = li,
			isFolder = False
		)

	def Init(self):
		self.base_url		= sys.argv[0]
		self.addon_handle	= int(sys.argv[1])
		self.args		= urlparse.parse_qs(sys.argv[2][1:])
	def Do(self):
		mode = self.args.get('option', None)
		if mode is None:
			self.doOption('list')
		else:
			self.doOption(mode[0])
	def Exit(self):
		pass

addon = FMRadio()
addon.Init()
addon.Do()
addon.Exit()
del addon

**Comment by glorang** [comment]
Many thanks for your updated addon! Sorry for not getting back earlier, too much other stuff todo.

Are you running this on the lastest kodi 16.0 / 16.1 ? I'm still on 15 but get an error "RuntimeError: Could not get AddonPtr given a script id of plugin.audio.rtlfm" on both the settings & language variables, they seem unused in any case?

I'll see if I can update my Kodi installation somewhere in the future.

Thx,
Geert
